{% set name = "jupyter_scheduler" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_scheduler-{{ version }}.tar.gz
  sha256: 586d3a6b76f4fb722eb611d7ff767ed01c60fbd5c9214b5c5509642d4eea9f78

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . -vv
    requirements:
      host:
        - python >=3.7,<3.12
        - hatchling >=1.3.1
        - jupyterlab >=4.0,<5
        - pip
        - hatch-jupyter-builder
      run:
        - python >=3.7,<3.12
        - jupyter_server >=1.6,<3
        - traitlets >=5.0,<6
        - nbconvert >=7.0,<8
        - pydantic >=1.10,<3
        - sqlalchemy >=2.0,<3
        - croniter >=1.4,<2
        - pytz ==2023.3
        - fsspec ==2023.6.0
        - psutil >=5.9,<6
    test:
      imports:
        - jupyter_scheduler
      commands:
        - pip check
      requires:
        - pip

  - name: jupyter-scheduler
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - jupyter_scheduler

about:
  summary: A JupyterLab extension for running notebook jobs
  home: https://github.com/jupyter-server/jupyter-scheduler
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - andrii-i
    - dlqqq
    - JasonWeill
